#!/usr/bin/env python
import random, sys

fin = sys.argv[1]
fout = sys.argv[2]
n = int(sys.argv[3])
seed = int(sys.argv[4])

random.seed(seed)
with open(fin) as handle_in:
    for idx, line in enumerate(handle_in):
        pass

random_indices = random.sample(range(idx), n)
random_indices = set(random_indices)

handle_out = open(fout, 'w') if fout != '-' else sys.stdout
with open(fin) as handle_in:
    for i, line in enumerate(handle_in):
        if i in random_indices:
            handle_out.write(line)

handle_out.close()
